### PR TITLE
exclude_func for users to discern when the scrollbar renders

### LINKED ISSUE #7: [Feature request] Add function to allow custom ignoring from the user
Say I want to ignore the scrollbar in float windows, having something like:

```lua
  require("scrollbar").setup({
    exclude_func = function(winid, bufnr)
      if not vim.api.nvim_win_is_valid(winid) then
        return true
      end

      local is_floating = vim.api.nvim_win_get_config(winid).relative ~= ""

      local filetype = vim.api.nvim_buf_get_option(bufnr, "filetype")
      local exclude_filetype = {
        TelescopePrompt = true,
        [""] = true,
      }

      local buftype = vim.api.nvim_buf_get_option(bufnr, "buftype")
      local exclude_buftype = {
        terminal = true,
        prompt = true,
      }

      return is_floating or exclude_buftype[buftype] or exclude_filetype[filetype]
    end,
  })
```

which is likely a bit more complicated and would require adding options for each kind of filtering the user wants to do. Having a function like this (can even provide some default options) seems a bit easier.

This would be in addition to `exclude_filetypes` or just replace it as that option would likely become redundant.

I will make a _PR_ for this in a bit.

### PR DESCRIPTION
**Pull request by levouh**
There might be some issues here with the fact that we are using the current window/buffer (#8 and #6) so leaving this as a draft for now as fixes might need to come before this.

Closes #7

### CODE REVIEW

**Comment by levouh** [comment]
This is a little bit confusing (at least as I think about it) to have a function that returns "if the scrollbar should not be drawn". Perhaps it would be a better idea to have the option mirror the name of the function; just `should_render` which returns `true` to draw the window and `false` to not.

**Comment by tbung** [comment]
I think `exclude_func` works well with `exclude_filetype` and `exclude_buftype`, but if it is named like that it should probably return `false` by default, because it does *not* exclude, it should then be switched in `should_render`.

**Comment by petertriho** [comment]
I'm not sure if it'll be better/worse but something like `render_callback`, and just a bare `return` if we don't want to render could work as well

**Comment by levouh** [comment]
I assume you mean passing a function that the user can just call if they want to draw the scrollbar @petertriho? I changed it to return whether or not the scrollbar should be drawn, rather than the double negative that existed before that makes it a bit confusing.

**Comment by petertriho** [comment]
What I mean is something like 

```
M.render = function()
       vim.api.nvim_buf_clear_namespace(0, NAMESPACE, 0, -1)
       config.render_callback(config)

		.... etc
end

config.render_callback = function()
       if vim.tbl_contains(config.excluded_filetypes, vim.bo.filetype) then
            return
       end
end

```

**Comment by levouh** [comment]
I actually think the implementation to show/hide this works in the same manner as @tbung mentioned. I can just set `show = false` and then setup autocommands to show the scrollbar when I want it shown.

**Pull request closed without merging**
